"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_darkpurple)\
$os\
$username\
[](bg:color_black fg:color_darkpurple)\
$docker_context\
$directory\
[](fg:color_black bg:color_fg0)\
$custom\
[](color_bg1)\
$time\
[](fg:color_bg1)\
$line_break$sudo$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#ececec'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#227f51'
color_orange = '#d65d0e'
color_purple = '#6e0087'
color_darkpurple = '#3e0096'
color_black = '#000000'
color_red = '#b80600'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_darkpurple fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_darkpurple fg:color_fg0"
style_root = "bg:color_darkpurple fg:color_fg0"
format = '[  $user ]($style)'
aliases = {  "ROOT" = "root"}

[directory]
style = "fg:color_fg0 bg:color_black"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "Documents 󰈙"
"Downloads" = "Downloads "
"Music" = "Music 󰝚"
"Pictures" = "Pictures "
"Developer" = "Developer 󰲋"
"~" = "~"

#############################################################
###########-------------- other -------------################
#############################################################
[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ 󱦟 $time ](fg:color_fg0 bg:color_bg1)]($style)'

[custom.filetypes]
command = "list_filetypes"
when = "true"
format = "[ $output ](fg:color_black bg:color_fg0)[](bg:color_black fg:color_fg0) "
shell = ["zsh", "-f", "--no-rcs", "--no-globalrcs"]

[line_break]
disabled = false

[sudo]
style = "color_red"
symbol = "[ ]($style)"
disabled = false

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[character]
disabled = false
success_symbol = '[󱞪](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[󱞦](bold fg:color_green)'
vimcmd_replace_one_symbol = '[󱞦](bold fg:color_purple)'
vimcmd_replace_symbol = '[󱞦](bold fg:color_purple)'
vimcmd_visual_symbol = '[󱞦](bold fg:color_yellow)'
